name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify Java Installation (Optional)
      run: |
        java -version  # Check if Java is already installed

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest tests/test_app.py

    - name: Build
      run: |
        echo "Building the application..."

    - name: Install SonarScanner
      run: |
        curl -L -o sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip -q sonar-scanner-cli.zip
        rm sonar-scanner-cli.zip
        mv sonar-scanner-4.6.2.2472-linux sonar-scanner
        echo "sonar.host.url=https://sonarcloud.io" >> sonar-scanner/conf/sonar-scanner.properties
        echo "sonar.login=${{ secrets.SONAR_TOKEN }}" >> sonar-scanner/conf/sonar-scanner.properties

    - name: Run SonarCloud Analysis
      run: |
        sonar-scanner/bin/sonar-scanner
