name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verify Java Installation (Optional)
      run: |
        java -version  # Check if Java is already installed

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest tests/test_app.py

    - name: Build
      run: |
        echo "Building the application..."

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
