name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest tests/test_app.py

      - name: Build
        run: |
          echo "Building the application..."

      - name: Set up Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'openjdk'

      - name: Install SonarScanner
        run: |
            curl -L -o sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            unzip -q sonar-scanner-cli.zip
            rm sonar-scanner-cli.zip
            mv sonar-scanner-4.6.2.2472-linux sonar-scanner

            # Set JAVA_HOME
            echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

      - name: Run SonarCloud Analysis
        run: |
            export JAVA_HOME=$JAVA_HOME
            sonar-scanner/bin/sonar-scanner -Dproject.settings=sonar-project.properties
